services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - docker-network

networks:
  docker-network:
    name: docker-network
    driver: bridge
