const movieRecommendations = {
  page: 1,
  results: [
    {
      backdrop_path: "/k24eZq5I3jyz4htPkZCRpnUmBzE.jpg",
      id: 1156593,
      title: "Your Fault",
      original_title: "Culpa tuya",
      overview:
        "The love between Noah and Nick seems unwavering despite their parents' attempts to separate them. But his job and her entry into college open up their lives to new relationships that will shake the foundations of both their relationship and the Leister family itself.",
      poster_path: "/1sQA7lfcF9yUyoLYC0e6Zo3jmxE.jpg",
      media_type: "movie",
      adult: false,
      original_language: "es",
      genre_ids: [10749, 18],
      popularity: 2310.635,
      release_date: "2024-12-26",
      video: false,
      vote_average: 7.139,
      vote_count: 779,
    },
    {
      backdrop_path: "/uKb22E0nlzr914bA9KyA5CVCOlV.jpg",
      id: 402431,
      title: "Wicked",
      original_title: "Wicked",
      overview:
        "In the land of Oz, ostracized and misunderstood green-skinned Elphaba is forced to share a room with the popular aristocrat Glinda at Shiz University, and the two's unlikely friendship is tested as they begin to fulfill their respective destinies as Glinda the Good and the Wicked Witch of the West.",
      poster_path: "/xDGbZ0JJ3mYaGKy4Nzd9Kph6M9L.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [18, 10749, 14],
      popularity: 2260.092,
      release_date: "2024-11-20",
      video: false,
      vote_average: 7.3,
      vote_count: 1144,
    },
    {
      backdrop_path: "/wYkrnn3eQY3vzMz4DJVMAgpQYYy.jpg",
      id: 1082195,
      title: "The Order",
      original_title: "The Order",
      overview:
        "A string of violent robberies in the Pacific Northwest leads a veteran FBI agent into a domestic terrorist plot to overthrow the federal government.",
      poster_path: "/1bJ2652AUnuK1WhlR0GLbJKVqMF.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [80, 18, 53],
      popularity: 64.29,
      release_date: "2024-12-05",
      video: false,
      vote_average: 6.7,
      vote_count: 106,
    },
    {
      backdrop_path: "/9Qq8InnodUYs8zdam8Zj967i6RO.jpg",
      id: 1106739,
      title: "Juror #2",
      original_title: "Juror #2",
      overview:
        "While serving as a juror in a high profile murder trial, family man Justin Kemp finds himself struggling with a serious moral dilemma…one he could use to sway the jury verdict and potentially convict—or free—the accused killer.",
      poster_path: "/utLESWj433xnIc1ss9TZjRI9SSl.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [80, 18],
      popularity: 195.702,
      release_date: "2024-10-30",
      video: false,
      vote_average: 6.959,
      vote_count: 1097,
    },
    {
      backdrop_path: "/zpaodBqO2lcwJh2SQrFFf1Rn8Jy.jpg",
      id: 1100099,
      title: "We Live in Time",
      original_title: "We Live in Time",
      overview:
        "An up-and-coming chef and a recent divorcée find their lives forever changed when a chance encounter brings them together, in a decade-spanning, deeply moving romance.",
      poster_path: "/ssFS25CiYQvRJqErqaEyHuVgyH7.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [10749, 18],
      popularity: 309.047,
      release_date: "2024-10-10",
      video: false,
      vote_average: 7.524,
      vote_count: 400,
    },
    {
      backdrop_path: "/tElnmtQ6yz1PjN1kePNl8yMSb59.jpg",
      id: 1241982,
      title: "Moana 2",
      original_title: "Moana 2",
      overview:
        "After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she's ever faced.",
      poster_path: "/m0SbwFNCa9epW1X60deLqTHiP7x.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [16, 12, 10751, 35],
      popularity: 2127.698,
      release_date: "2024-11-21",
      video: false,
      vote_average: 7.013,
      vote_count: 800,
    },
    {
      backdrop_path: "/6neVLKBU4DaWAwpWFhfCpV6yuqN.jpg",
      id: 1290287,
      title: "Hot Frosty",
      original_title: "Hot Frosty",
      overview:
        "When a young widow's magic scarf brings a dashing snowman to life, can he help her rediscover romance, laughter and holiday cheer before he melts away?",
      poster_path: "/waW6R5WJQSxq65gwBkvnKlseU6n.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [10749, 35],
      popularity: 34.502,
      release_date: "2024-11-12",
      video: false,
      vote_average: 6,
      vote_count: 227,
    },
    {
      backdrop_path: "/cjEcqdRdPQJhYre3HUAc5538Gk8.jpg",
      id: 845781,
      title: "Red One",
      original_title: "Red One",
      overview:
        "After Santa Claus (codename: Red One) is kidnapped, the North Pole's Head of Security must team up with the world's most infamous tracker in a globe-trotting, action-packed mission to save Christmas.",
      poster_path: "/cdqLnri3NEGcmfnqwk2TSIYtddg.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 14, 35],
      popularity: 1892.703,
      release_date: "2024-10-31",
      video: false,
      vote_average: 7.1,
      vote_count: 1921,
    },
    {
      backdrop_path: "/66nlC5LDZmDUWONGkUZT2BrOszG.jpg",
      id: 974576,
      title: "Conclave",
      original_title: "Conclave",
      overview:
        "After the unexpected death of the Pope, Cardinal Lawrence is tasked with managing the covert and ancient ritual of electing a new one. Sequestered in the Vatican with the Catholic Church’s most powerful leaders until the process is complete, Lawrence finds himself at the center of a conspiracy that could lead to its downfall.",
      poster_path: "/m5x8D0bZ3eKqIVWZ5y7TnZ2oTVg.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [18],
      popularity: 234.58,
      release_date: "2024-10-25",
      video: false,
      vote_average: 7.1,
      vote_count: 754,
    },
    {
      backdrop_path: "/zOpe0eHsq0A2NvNyBbtT6sj53qV.jpg",
      id: 939243,
      title: "Sonic the Hedgehog 3",
      original_title: "Sonic the Hedgehog 3",
      overview:
        "Sonic, Knuckles, and Tails reunite against a powerful new adversary, Shadow, a mysterious villain with powers unlike anything they have faced before. With their abilities outmatched in every way, Team Sonic must seek out an unlikely alliance in hopes of stopping Shadow and protecting the planet.",
      poster_path: "/d8Ryb8AunYAuycVKDp5HpdWPKgC.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 878, 35, 10751],
      popularity: 4115.631,
      release_date: "2024-12-19",
      video: false,
      vote_average: 7.601,
      vote_count: 437,
    },
    {
      backdrop_path: "/jhk6D8pim3yaByu1801kMoxXFaX.jpg",
      id: 98,
      title: "Gladiator",
      original_title: "Gladiator",
      overview:
        "After the death of Emperor Marcus Aurelius, his devious son takes power and demotes Maximus, one of Rome's most capable generals who Marcus preferred. Eventually, Maximus is forced to become a gladiator and battle to the death against other men for the amusement of paying audiences.",
      poster_path: "/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 18, 12],
      popularity: 233.246,
      release_date: "2000-05-04",
      video: false,
      vote_average: 8.22,
      vote_count: 19147,
    },
    {
      backdrop_path: "/ag66gJCiZ06q1GSJuQlhGLi3Udx.jpg",
      id: 1138194,
      title: "Heretic",
      original_title: "Heretic",
      overview:
        "Two young missionaries are forced to prove their faith when they knock on the wrong door and are greeted by a diabolical Mr. Reed, becoming ensnared in his deadly game of cat-and-mouse.",
      poster_path: "/5HJqjCTcaE1TFwnNh3Dn21be2es.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [27, 53],
      popularity: 598.61,
      release_date: "2024-10-31",
      video: false,
      vote_average: 7.2,
      vote_count: 789,
    },
    {
      backdrop_path: "/oHPoF0Gzu8xwK4CtdXDaWdcuZxZ.jpg",
      id: 762509,
      title: "Mufasa: The Lion King",
      original_title: "Mufasa: The Lion King",
      overview:
        "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
      poster_path: "/iBqXjFkAozQ1z2sfAiWwBimbiJX.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [12, 10751, 16],
      popularity: 2684.622,
      release_date: "2024-12-18",
      video: false,
      vote_average: 7.5,
      vote_count: 546,
    },
    {
      backdrop_path: "/ie8OSgIHEl6yQiGJ90dsyBWOpQA.jpg",
      id: 839033,
      title: "The Lord of the Rings: The War of the Rohirrim",
      original_title: "The Lord of the Rings: The War of the Rohirrim",
      overview:
        "A sudden attack by Wulf, a clever and traitorous lord of Rohan seeking vengeance for the death of his father, forces Helm Hammerhand, the King of Rohan, and his people to make a daring last stand in the ancient stronghold of the Hornburg.",
      poster_path: "/cXzCOx1hUuU9CfmiEv6rXjb6EqU.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [16, 14, 28, 12],
      popularity: 1984.581,
      release_date: "2024-12-05",
      video: false,
      vote_average: 6.5,
      vote_count: 276,
    },
    {
      backdrop_path: "/au3o84ub27qTZiMiEc9UYzN74V3.jpg",
      id: 1035048,
      title: "Elevation",
      original_title: "Elevation",
      overview:
        "A single father and two women venture from the safety of their homes to face monstrous creatures to save the life of a young boy.",
      poster_path: "/9knPvD6GLtl1w4pamRomyQKHXyj.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 878, 53],
      popularity: 1408.767,
      release_date: "2024-11-07",
      video: false,
      vote_average: 6.2,
      vote_count: 298,
    },
    {
      backdrop_path: "/v9Du2HC3hlknAvGlWhquRbeifwW.jpg",
      id: 539972,
      title: "Kraven the Hunter",
      original_title: "Kraven the Hunter",
      overview:
        "Kraven Kravinoff's complex relationship with his ruthless gangster father, Nikolai, starts him down a path of vengeance with brutal consequences, motivating him to become not only the greatest hunter in the world, but also one of its most feared.",
      poster_path: "/i47IUSsN126K11JUzqQIOi1Mg1M.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 12, 53],
      popularity: 527.719,
      release_date: "2024-12-11",
      video: false,
      vote_average: 5.9,
      vote_count: 291,
    },
    {
      backdrop_path: "/vZG7PrX9HmdgL5qfZRjhJsFYEIA.jpg",
      id: 912649,
      title: "Venom: The Last Dance",
      original_title: "Venom: The Last Dance",
      overview:
        "Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision that will bring the curtains down on Venom and Eddie's last dance.",
      poster_path: "/aosm8NMQ3UyoBVpSxyimorCQykC.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 878, 12],
      popularity: 2911.214,
      release_date: "2024-10-22",
      video: false,
      vote_average: 6.803,
      vote_count: 2254,
    },
    {
      backdrop_path: "/4FnbeuCnsN3MT6omPrivl2ttJ8o.jpg",
      id: 1061699,
      title: "The Six Triple Eight",
      original_title: "The Six Triple Eight",
      overview:
        "During World War II, the US Army's only all-Black, all-women battalion takes on an impossible mission: sorting through a three-year backlog of 17 million pieces of mail that hadn't been delivered to American soldiers and finish within six months.",
      poster_path: "/7tvAnzZj9e9AjdoHaN9jshm2Cjw.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [18, 10752, 36],
      popularity: 259.284,
      release_date: "2024-12-06",
      video: false,
      vote_average: 7.724,
      vote_count: 284,
    },
    {
      backdrop_path: "/evFChfYeD2LqobEJf8iQsrYcGTw.jpg",
      id: 1182387,
      title: "Armor",
      original_title: "Armor",
      overview:
        "Armored truck security guard James Brody is working with his son Casey transporting millions of dollars between banks when a team of thieves led by Rook orchestrate a takeover of their truck to seize the riches. Following a violent car chase, Rook soon has the armored truck surrounded and James and Casey find themselves cornered onto a decrepit bridge.",
      poster_path: "/pnXLFioDeftqjlCVlRmXvIdMsdP.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 80, 53],
      popularity: 515.23,
      release_date: "2024-10-30",
      video: false,
      vote_average: 5.6,
      vote_count: 129,
    },
    {
      backdrop_path: "/iR79ciqhtaZ9BE7YFA1HpCHQgX4.jpg",
      id: 1100782,
      title: "Smile 2",
      original_title: "Smile 2",
      overview:
        "About to embark on a new world tour, global pop sensation Skye Riley begins experiencing increasingly terrifying and inexplicable events. Overwhelmed by the escalating horrors and the pressures of fame, Skye is forced to face her dark past to regain control of her life before it spirals out of control.",
      poster_path: "/ht8Uv9QPv9y7K0RvUyJIaXOZTfd.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [27, 9648],
      popularity: 506.422,
      release_date: "2024-10-16",
      video: false,
      vote_average: 6.63,
      vote_count: 1124,
    },
  ],
  total_pages: 2,
  total_results: 40,
};
