const movieSimilar = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/9H8wGFwKKt2ADRhg2odywTg1NCZ.jpg",
      genre_ids: [878, 35, 12, 14, 28],
      id: 1680,
      original_language: "ja",
      original_title: "キングコング対ゴジラ",
      overview:
        "The advertising director of Pacific Pharmaceuticals, frustrated with the low ratings of their sponsored TV program, seeks a more sensationalist approach. He orders his staff to Faro Island to capture King Kong for exploitation. As Godzilla re-emerges, a media frenzy generates with Pacific looking to capitalize off of the ultimate battle.",
      popularity: 20.124,
      poster_path: "/8djxObchUlEVcLdNl60EJm8EHZ0.jpg",
      release_date: "1962-08-11",
      title: "King Kong vs. Godzilla",
      video: false,
      vote_average: 6.8,
      vote_count: 305,
    },
    {
      adult: false,
      backdrop_path: "/dKMpMwJB9Aq1fflGAcVfagfG0R5.jpg",
      genre_ids: [18, 28, 878],
      id: 1682,
      original_language: "ja",
      original_title: "モスラ対ゴジラ",
      overview:
        "Journalists Ichiro Sakai and Junko cover the wreckage of a typhoon when an enormous egg is found and claimed by greedy entrepreneurs. Mothra's fairies arrive and are aided by the journalists in a plea for its return. As their requests are denied, Godzilla arises near Nagoya and the people of Infant Island must decide if they are willing to answer Japan's own pleas for help.",
      popularity: 15.999,
      poster_path: "/y49vvM03gpuyhpyMc1f55VrNkP3.jpg",
      release_date: "1964-04-29",
      title: "Mothra vs. Godzilla",
      video: false,
      vote_average: 7,
      vote_count: 287,
    },
    {
      adult: false,
      backdrop_path: "/7COZZS8Yfe13pEyjuF4k5WGsLEA.jpg",
      genre_ids: [28, 878],
      id: 1687,
      original_language: "en",
      original_title: "Escape from the Planet of the Apes",
      overview:
        "The world is shocked by the appearance of three talking chimpanzees, who arrived mysteriously in a spacecraft. Intrigued by their intelligence, humans use them for research - until the apes attempt to escape.",
      popularity: 27.789,
      poster_path: "/AnbLVdUEroTfHTUVAJCxkL4R0IH.jpg",
      release_date: "1971-05-20",
      title: "Escape from the Planet of the Apes",
      video: false,
      vote_average: 6.378,
      vote_count: 1084,
    },
    {
      adult: false,
      backdrop_path: "/o1a5hUxzdXtz1vmu240euYHNe8E.jpg",
      genre_ids: [18, 27, 80],
      id: 1696,
      original_language: "en",
      original_title: "The Devil's Rejects",
      overview:
        "The murderous, backwoods Firefly family take to the road to escape the vengeful Sheriff Wydell, who is not afraid of being as ruthless as his target.",
      popularity: 16.397,
      poster_path: "/drZz4AuI7trq6BxlH9Xa4v4O0Pb.jpg",
      release_date: "2005-07-22",
      title: "The Devil's Rejects",
      video: false,
      vote_average: 6.754,
      vote_count: 1419,
    },
    {
      adult: false,
      backdrop_path: "/uoOD6qqz4QFhgvhdsrrQUmkmAMc.jpg",
      genre_ids: [12, 28, 14],
      id: 1734,
      original_language: "en",
      original_title: "The Mummy Returns",
      overview:
        "Rick and Evelyn O’Connell, along with their 8-year-old son Alex, discover the key to the legendary Scorpion King’s might: the fabled Bracelet of Anubis. Unfortunately, a newly resurrected Imhotep has designs on the bracelet as well, and isn’t above kidnapping its new bearer, Alex, to gain control of Anubis’s otherworldly army.",
      popularity: 76.591,
      poster_path: "/kdJsW7hcy1lrj7tdMPycTAQPAiR.jpg",
      release_date: "2001-05-04",
      title: "The Mummy Returns",
      video: false,
      vote_average: 6.4,
      vote_count: 7054,
    },
    {
      adult: false,
      backdrop_path: "/9Qs9oyn4iE8QtQjGZ0Hp2WyYNXT.jpg",
      genre_ids: [18, 10752],
      id: 28,
      original_language: "en",
      original_title: "Apocalypse Now",
      overview:
        'At the height of the Vietnam war, Captain Benjamin Willard is sent on a dangerous mission that, officially, "does not exist, nor will it ever exist." His goal is to locate - and eliminate - a mysterious Green Beret Colonel named Walter Kurtz, who has been leading his personal army on illegal guerrilla missions into enemy territory.',
      popularity: 66.281,
      poster_path: "/gQB8Y5RCMkv2zwzFHbUJX3kAhvA.jpg",
      release_date: "1979-05-19",
      title: "Apocalypse Now",
      video: false,
      vote_average: 8.275,
      vote_count: 8277,
    },
    {
      adult: false,
      backdrop_path: "/bIA65PCRtIQfBvIoKohJbtOPl3M.jpg",
      genre_ids: [28, 35, 80],
      id: 96,
      original_language: "en",
      original_title: "Beverly Hills Cop II",
      overview:
        'Axel Foley returns to the land of sunshine and palm trees to investigate the near-fatal shooting of police Captain Andrew Bogomil. With the help of Sgt. Taggart and Det. Rosewood, they soon uncover that the shooting is associated with a series of "alphabet" robberies masterminded by a heartless weapons kingpin—and the chase is on.',
      popularity: 29.174,
      poster_path: "/egDakU8O5yUwpUJP9IMAUVtIDll.jpg",
      release_date: "1987-05-18",
      title: "Beverly Hills Cop II",
      video: false,
      vote_average: 6.507,
      vote_count: 2547,
    },
    {
      adult: false,
      backdrop_path: "/jhk6D8pim3yaByu1801kMoxXFaX.jpg",
      genre_ids: [28, 18, 12],
      id: 98,
      original_language: "en",
      original_title: "Gladiator",
      overview:
        "After the death of Emperor Marcus Aurelius, his devious son takes power and demotes Maximus, one of Rome's most capable generals who Marcus preferred. Eventually, Maximus is forced to become a gladiator and battle to the death against other men for the amusement of paying audiences.",
      popularity: 233.246,
      poster_path: "/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
      release_date: "2000-05-04",
      title: "Gladiator",
      video: false,
      vote_average: 8.22,
      vote_count: 19147,
    },
    {
      adult: false,
      backdrop_path: "/6G73mNyooWAEQTpckPSnFxFoNmc.jpg",
      genre_ids: [12, 14, 28],
      id: 121,
      original_language: "en",
      original_title: "The Lord of the Rings: The Two Towers",
      overview:
        "Frodo Baggins and the other members of the Fellowship continue on their sacred quest to destroy the One Ring--but on separate paths. Their destinies lie at two towers--Orthanc Tower in Isengard, where the corrupt wizard Saruman awaits, and Sauron's fortress at Barad-dur, deep within the dark lands of Mordor. Frodo and Sam are trekking to Mordor to destroy the One Ring of Power while Gimli, Legolas and Aragorn search for the orc-captured Merry and Pippin. All along, nefarious wizard Saruman awaits the Fellowship members at the Orthanc Tower in Isengard.",
      popularity: 117.752,
      poster_path: "/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg",
      release_date: "2002-12-18",
      title: "The Lord of the Rings: The Two Towers",
      video: false,
      vote_average: 8.399,
      vote_count: 22054,
    },
    {
      adult: false,
      backdrop_path: "/5JrZAtyk3LwiiAWLW0kwz41XZJC.jpg",
      genre_ids: [12, 14, 28],
      id: 122,
      original_language: "en",
      original_title: "The Lord of the Rings: The Return of the King",
      overview:
        "As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.​",
      popularity: 156.052,
      poster_path: "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
      release_date: "2003-12-17",
      title: "The Lord of the Rings: The Return of the King",
      video: false,
      vote_average: 8.5,
      vote_count: 24454,
    },
    {
      adult: false,
      backdrop_path: "/8G6HCS82vNxgg5wp7oBDSk32XpF.jpg",
      genre_ids: [28, 12, 878],
      id: 558,
      original_language: "en",
      original_title: "Spider-Man 2",
      overview:
        "Peter Parker is going through a major identity crisis. Burned out from being Spider-Man, he decides to shelve his superhero alter ego, which leaves the city suffering in the wake of carnage left by the evil Doc Ock. In the meantime, Parker still can't act on his feelings for Mary Jane Watson, a girl he's loved since childhood. A certain anger begins to brew in his best friend Harry Osborn as well...",
      popularity: 41.511,
      poster_path: "/olxpyq9kJAZ2NU1siLshhhXEPR7.jpg",
      release_date: "2004-06-25",
      title: "Spider-Man 2",
      video: false,
      vote_average: 7.288,
      vote_count: 15199,
    },
    {
      adult: false,
      backdrop_path: "/w1oD1MzHjnBJc5snKupIQaSBLIh.jpg",
      genre_ids: [28, 12, 878],
      id: 559,
      original_language: "en",
      original_title: "Spider-Man 3",
      overview:
        "The seemingly invincible Spider-Man goes up against an all-new crop of villains—including the shape-shifting Sandman. While Spider-Man’s superpowers are altered by an alien organism, his alter ego, Peter Parker, deals with nemesis Eddie Brock and also gets caught up in a love triangle.",
      popularity: 92.162,
      poster_path: "/qFmwhVUoUSXjkKRmca5yGDEXBIj.jpg",
      release_date: "2007-05-01",
      title: "Spider-Man 3",
      video: false,
      vote_average: 6.4,
      vote_count: 14185,
    },
    {
      adult: false,
      backdrop_path: "/cJyQfwSEa5IjOdeNTuiWjciVbou.jpg",
      genre_ids: [12, 53, 27],
      id: 580,
      original_language: "en",
      original_title: "Jaws: The Revenge",
      overview:
        "After another deadly shark attack, Ellen Brody decides she has had enough of New England's Amity Island and moves to the Caribbean to join her son, Michael, and his family. But a great white shark has followed her there, hungry for more lives.",
      popularity: 21.818,
      poster_path: "/ebYw9tR0iqBzDGA6HVBhtd2xJM3.jpg",
      release_date: "1987-07-17",
      title: "Jaws: The Revenge",
      video: false,
      vote_average: 4.057,
      vote_count: 1051,
    },
    {
      adult: false,
      backdrop_path: "/sCzcYW9h55WcesOqA12cgEr9Exw.jpg",
      genre_ids: [18, 10749],
      id: 597,
      original_language: "en",
      original_title: "Titanic",
      overview:
        "101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic, 84 years later. A young Rose boards the ship with her mother and fiancé. Meanwhile, Jack Dawson and Fabrizio De Rossi win third-class tickets aboard the ship. Rose tells the whole story from Titanic's departure through to its death—on its first and last voyage—on April 15, 1912.",
      popularity: 196.347,
      poster_path: "/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
      release_date: "1997-11-18",
      title: "Titanic",
      video: false,
      vote_average: 7.907,
      vote_count: 25525,
    },
    {
      adult: false,
      backdrop_path: "/pulJ1iY7GVeppMRipiR7ZGDW7EW.jpg",
      genre_ids: [18],
      id: 615,
      original_language: "en",
      original_title: "The Passion of the Christ",
      overview:
        "A graphic portrayal of the last twelve hours of Jesus of Nazareth's life.",
      popularity: 70.2,
      poster_path: "/v9f9MMrq2nGQrN7cHnQRmEq9lSE.jpg",
      release_date: "2004-02-25",
      title: "The Passion of the Christ",
      video: false,
      vote_average: 7.502,
      vote_count: 4611,
    },
    {
      adult: false,
      backdrop_path: "/uPYa165sraN2c8gZBM9C47g3JoU.jpg",
      genre_ids: [18, 80],
      id: 311,
      original_language: "en",
      original_title: "Once Upon a Time in America",
      overview:
        "A former Prohibition-era Jewish gangster returns to the Lower East Side of Manhattan over thirty years later, where he once again must confront the ghosts and regrets of his old life.",
      popularity: 50.31,
      poster_path: "/i0enkzsL5dPeneWnjl1fCWm6L7k.jpg",
      release_date: "1984-05-23",
      title: "Once Upon a Time in America",
      video: false,
      vote_average: 8.4,
      vote_count: 5437,
    },
    {
      adult: false,
      backdrop_path: "/w9eBtIHHpGgGfjqnEAJM3s7mCOa.jpg",
      genre_ids: [12, 28, 878],
      id: 330,
      original_language: "en",
      original_title: "The Lost World: Jurassic Park",
      overview:
        "Four years after Jurassic Park's genetically bred dinosaurs ran amok, multimillionaire John Hammond shocks chaos theorist Ian Malcolm by revealing that he has been breeding more beasties at a secret location. Malcolm, his paleontologist ladylove and a wildlife videographer join an expedition to document the lethal lizards' natural behavior in this action-packed thriller.",
      popularity: 2.505,
      poster_path: "/jElpCJkSaRPYwIMwZY28gOKV7BK.jpg",
      release_date: "1997-05-23",
      title: "The Lost World: Jurassic Park",
      video: false,
      vote_average: 6.544,
      vote_count: 8394,
    },
    {
      adult: false,
      backdrop_path: "/sJNNMCc6B7KZIY3LH3JMYJJNH5j.jpg",
      genre_ids: [28, 18],
      id: 346,
      original_language: "ja",
      original_title: "七人の侍",
      overview:
        "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
      popularity: 41.118,
      poster_path: "/iAq0sq42vKTLneVGqHn1D4GzgrM.jpg",
      release_date: "1954-04-26",
      title: "Seven Samurai",
      video: false,
      vote_average: 8.5,
      vote_count: 3736,
    },
    {
      adult: false,
      backdrop_path: "/bYJv39whWTAOWO0mv7oUija8GgM.jpg",
      genre_ids: [28, 12],
      id: 575264,
      original_language: "en",
      original_title: "Mission: Impossible - Dead Reckoning Part One",
      overview:
        "Ethan Hunt and his IMF team embark on their most dangerous mission yet: To track down a terrifying new weapon that threatens all of humanity before it falls into the wrong hands. With control of the future and the world's fate at stake and dark forces from Ethan's past closing in, a deadly race around the globe begins. Confronted by a mysterious, all-powerful enemy, Ethan must consider that nothing can matter more than his mission—not even the lives of those he cares about most.",
      popularity: 121.646,
      poster_path: "/NNxYkU70HPurnNCSiCjYAmacwm.jpg",
      release_date: "2023-07-08",
      title: "Mission: Impossible - Dead Reckoning Part One",
      video: false,
      vote_average: 7.5,
      vote_count: 3919,
    },
    {
      adult: false,
      backdrop_path: "/3hugi0xNkUG2SvrQI5GXIpDaf17.jpg",
      genre_ids: [28, 12, 53],
      id: 575265,
      original_language: "en",
      original_title: "Mission: Impossible - The Final Reckoning",
      overview:
        "After escaping a calamitous train crash, Ethan realizes The Entity is stashed aboard an old Russian submarine, but a foe from his past named Gabriel is also on the trail.",
      popularity: 108.286,
      poster_path: "/z53D72EAOxGRqdr7KXXWp9dJiDe.jpg",
      release_date: "2025-05-21",
      title: "Mission: Impossible - The Final Reckoning",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
  ],
  total_pages: 14449,
  total_results: 288964,
};
