const searchMultiSquid = {
  page: 1,
  results: [
    {
      backdrop_path: "/ukAmSyNdtWduHZfm27R2EOsguKt.jpg",
      id: 93405,
      name: "Squid Game",
      original_name: "오징어 게임",
      overview:
        "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits — with deadly high stakes.",
      poster_path: "/1QdXdRYfktUSONkl1oD5gc6Be0s.jpg",
      media_type: "tv",
      adult: false,
      original_language: "ko",
      genre_ids: [10759, 9648, 18],
      popularity: 8435.793,
      first_air_date: "2021-09-17",
      vote_average: 7.842,
      vote_count: 14832,
      origin_country: ["KR"],
    },
    {
      backdrop_path: "/lb2WCbppZ6iHfokg7ccmgjKPKNh.jpg",
      id: 1214667,
      title: "Making Squid Game: The Challenge",
      original_title: "Making Squid Game: The Challenge",
      overview:
        'Go behind the scenes and witness how the "Squid Game"-inspired reality show transformed from a scripted drama to a cutthroat, nail-biting competition.',
      poster_path: "/lUb97EhBhNBfQ9wmy8YMbiNLtGh.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [99],
      popularity: 1151.983,
      release_date: "2023-12-06",
      video: false,
      vote_average: 6.12,
      vote_count: 25,
    },
    {
      backdrop_path: "/fQsIJQxE1D0Y0NpWSKwo489y5px.jpg",
      id: 204082,
      name: "Squid Game: The Challenge",
      original_name: "Squid Game: The Challenge",
      overview:
        'In this reality competition show inspired by "Squid Game," 456 players put their skills to the ultimate test for a life-changing $4.56 million prize.',
      poster_path: "/y85L9DWoaM2MYNg1p8QRywxXJsa.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [10764],
      popularity: 1215.44,
      first_air_date: "2023-11-22",
      vote_average: 6.387,
      vote_count: 391,
      origin_country: ["GB"],
    },
    {
      backdrop_path: "/yO2IbbpnwcTdEOeNv4uyEHYdJPr.jpg",
      id: 82817,
      name: "Go Go Squid!",
      original_name: "亲爱的，热爱的",
      overview:
        "Tong Nian is a genius 19-year-old student with high IQ and low EQ, who is also a famous anime cosplay person and sings well. She’s falls in love at first sight with Han Shang Yan, who is a game genius in the e-sports world and never pays attention to the girls.",
      poster_path: "/xWnuIoWFejrYJXeEyJYUH4ILlVo.jpg",
      media_type: "tv",
      adult: false,
      original_language: "zh",
      genre_ids: [18],
      popularity: 58.08,
      first_air_date: "2019-07-09",
      vote_average: 8.1,
      vote_count: 159,
      origin_country: ["CN"],
    },
    {
      backdrop_path: "/JPuk8H588WIUragF1EQNPVQRcG.jpg",
      id: 35447,
      name: "Squid Girl",
      original_name: "侵略!イカ娘",
      overview:
        "Squid Girl has come to the land from the depths of the sea to conquer humanity in revenge for pollution of the ocean. Unfortunately she ruins the first house she uses as an invasion base and has to work to pay for repairs. Of course, she can't overcome the Aizawa sisters who manage the house, so who knows whether she can subjugate humankind.",
      poster_path: "/n9mhIbk2VE3bCDEm2aPsNZtZuOH.jpg",
      media_type: "tv",
      adult: false,
      original_language: "ja",
      genre_ids: [16, 35, 10765],
      popularity: 64.771,
      first_air_date: "2010-10-05",
      vote_average: 6.8,
      vote_count: 22,
      origin_country: ["JP"],
    },
    {
      backdrop_path: "/oD7pjI3KmToo7HBUcfTFxznmhY.jpg",
      id: 116133,
      name: "Go Go Squid 2: Dt.Appledog's Time",
      original_name: "我的时代，你的时代",
      overview:
        "Ai Qing – also known by her gaming handle Appledog – is one of the top robot combat players in the land. A model professional, smart, and friendly, she has no shortage of fans, among whom is Wu Bai – also known as DT.\n\nUnder Ai Qing’s tutelage, Wu Bai developed a keen passion for robot war contests and gaming, eventually becoming a star performer in his own right.\n\nNow, he has risen to become the robot combat scene’s biggest rising star, captaining a promising new team named Pirate, which threatens to outshine even Ai Qing’s powerful Appledog team.\n\nDespite their professional rivalry, the duo has remained close, and their feelings for one another continue to grow, with romance possibly in the cards.\n\nThe ultimate challenge will come at the annual Robot Combat Competition, where the teams Pirate, Appledog, and others will duke it out for a coveted trophy!",
      poster_path: "/tSYbZ9ulAZvCU6URzeBCKpwFR5I.jpg",
      media_type: "tv",
      adult: false,
      original_language: "zh",
      genre_ids: [18],
      popularity: 21.612,
      first_air_date: "2021-02-04",
      vote_average: 6.6,
      vote_count: 8,
      origin_country: ["CN"],
    },
    {
      backdrop_path: "/3gTIwbdGPE5d448o0dqOtYeDXBx.jpg",
      id: 539,
      name: "Squidbillies",
      original_name: "Squidbillies",
      overview:
        "Squidbillies is an animated television series about the Cuylers, an impoverished family of anthropomorphic hillbilly mud squids living in the Appalachian region of Georgia's mountains. The show is produced by Williams Street Studios for the Adult Swim programming block of Cartoon Network and premiered on October 16, 2005. It is written by Dave Willis, co-creator of Aqua Teen Hunger Force, and Jim Fortier, previously of The Brak Show, both of whom worked on the Adult Swim series Space Ghost Coast to Coast. The animation is done by Awesome Incorporated, with background design by Ben Prisk.",
      poster_path: "/ffXx3qq4eopQMof6M26tZ2yiiT3.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [35, 16],
      popularity: 316.971,
      first_air_date: "2004-11-07",
      vote_average: 6.8,
      vote_count: 71,
      origin_country: ["US"],
    },
    {
      id: 2762183,
      name: "Michael Squid",
      original_name: "Michael Squid",
      media_type: "person",
      adult: false,
      popularity: 0.001,
      gender: 0,
      known_for_department: "Directing",
      profile_path: null,
      known_for: [
        {
          backdrop_path: null,
          id: 738493,
          title: "The Chrysalis",
          original_title: "The Chrysalis",
          overview:
            "A young man moves in with his mother, a retired entomologist, to assist her battle with dementia. His stay quickly descends into a nightmare as his mother's aggression and strange behavior gives light to something more insidious at play.",
          poster_path: "/bKSGQ0Ng7uGyIaC1iRyxvwCYGam.jpg",
          media_type: "movie",
          adult: false,
          original_language: "en",
          genre_ids: [27],
          popularity: 0.988,
          release_date: "2020-05-01",
          video: false,
          vote_average: 5.5,
          vote_count: 7,
        },
        {
          backdrop_path: null,
          id: 876974,
          title: "Dice",
          original_title: "Dice",
          overview:
            "A man facing financial troubles stumbles across a bizarre and sinister solution to his predicament. He soon finds himself in a spiraling descent into darkness as dependence takes the reins.",
          poster_path: "/xT3mHV2YdIBn2wvueNLIyVWI7uV.jpg",
          media_type: "movie",
          adult: false,
          original_language: "en",
          genre_ids: [],
          popularity: 0.083,
          release_date: "",
          video: false,
          vote_average: 7,
          vote_count: 1,
        },
        {
          backdrop_path: null,
          id: 1063121,
          title: "The Order",
          original_title: "The Order",
          overview:
            "A food delivery driver struggling to get by accepts an extremely high-paying gig. It's soon clear, however, that this order is anything but ordinary.",
          poster_path: "/dGcF35UA6EXTj2Ohkw78pN0yV6w.jpg",
          media_type: "movie",
          adult: false,
          original_language: "en",
          genre_ids: [27],
          popularity: 0.202,
          release_date: "",
          video: false,
          vote_average: 5,
          vote_count: 1,
        },
      ],
    },
    {
      backdrop_path: "/z2OHAVBfIhebu4RovbL2knnSw3n.jpg",
      id: 10707,
      title: "The Squid and the Whale",
      original_title: "The Squid and the Whale",
      overview:
        "Based on the true childhood experiences of Noah Baumbach and his brother, The Squid and the Whale tells the touching story of two young boys dealing with their parents' divorce in Brooklyn in the 1980s.",
      poster_path: "/nR5H15WnECRm0oMTHIqynFcXtiQ.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [35, 18],
      popularity: 12.883,
      release_date: "2005-10-05",
      video: false,
      vote_average: 6.9,
      vote_count: 962,
    },
    {
      backdrop_path: "/lu4khHVh8ZF9AbaxW26pp4yLubb.jpg",
      id: 1408248,
      title: "Squid Game: Fireplace",
      original_title: "오징어 게임: 벽난로",
      overview:
        "Come share a toast in the Front Man's lair — but tread carefully, for you’re playing with fire.",
      poster_path: "/wzWcY5MMJaezP4niGmmpdvluvaZ.jpg",
      media_type: "movie",
      adult: false,
      original_language: "ko",
      genre_ids: [],
      popularity: 111.138,
      release_date: "2024-12-12",
      video: false,
      vote_average: 6,
      vote_count: 26,
    },
    {
      id: 2864375,
      name: "A drawing of a squid",
      original_name: "A drawing of a squid",
      media_type: "person",
      adult: false,
      popularity: 0.001,
      gender: 0,
      known_for_department: "Acting",
      profile_path: null,
      known_for: [
        {
          backdrop_path: null,
          id: 766901,
          title: "Somebodyelse",
          original_title: "Somebodyelse",
          overview:
            "By connecting with an old friend,  struggling artist Max improves his drawing skills exponentially.",
          poster_path: "/iaCaDvEYfJ46pcZWp6vpKmku4gW.jpg",
          media_type: "movie",
          adult: false,
          original_language: "en",
          genre_ids: [18],
          popularity: 0.015,
          release_date: "2020-11-21",
          video: false,
          vote_average: 0,
          vote_count: 0,
        },
      ],
    },
    {
      id: 3812581,
      name: "Squid Sterling",
      original_name: "Squid Sterling",
      media_type: "person",
      adult: false,
      popularity: 0.001,
      gender: 0,
      known_for_department: "Acting",
      profile_path: null,
      known_for: [
        {
          backdrop_path: null,
          id: 154196,
          name: "OutBreak Wrestling Quarantine",
          original_name: "OutBreak Wrestling Quarantine",
          overview: "OutBreak Wrestling From Reading, Pennsylvania, USA",
          poster_path: null,
          media_type: "tv",
          adult: false,
          original_language: "en",
          genre_ids: [],
          popularity: 3.398,
          first_air_date: "2020-07-04",
          vote_average: 0,
          vote_count: 0,
          origin_country: ["US"],
        },
        {
          backdrop_path: null,
          id: 224707,
          name: "Back Breakers Wrestling Present's Chasing the Dream",
          original_name: "Back Breakers Wrestling Present's Chasing the Dream",
          overview: "Back Breakers Wrestling Present's Chasing the Dream",
          poster_path: null,
          media_type: "tv",
          adult: false,
          original_language: "en",
          genre_ids: [],
          popularity: 1.554,
          first_air_date: "2018-10-31",
          vote_average: 0,
          vote_count: 0,
          origin_country: ["US"],
        },
      ],
    },
    {
      id: 3666207,
      name: "Sam Squid Farrauto",
      original_name: "Sam Squid Farrauto",
      media_type: "person",
      adult: false,
      popularity: 0.001,
      gender: 0,
      known_for_department: "Acting",
      profile_path: null,
      known_for: [
        {
          backdrop_path: "/wfs0ItcT5eYQ2eFALdLGA4pFsna.jpg",
          id: 1005020,
          title: "Ouija Shark 2",
          original_title: "Ouija Shark 2",
          overview: "Sequel to the cult film Ouija Shark.",
          poster_path: "/4DY5LRO2Kc3rp2VvDoKBei0EZQc.jpg",
          media_type: "movie",
          adult: false,
          original_language: "en",
          genre_ids: [27, 14, 35],
          popularity: 1.653,
          release_date: "2023-09-01",
          video: false,
          vote_average: 5.3,
          vote_count: 3,
        },
      ],
    },
    {
      id: 2743936,
      name: "Sid the Squid",
      original_name: "Sid the Squid",
      media_type: "person",
      adult: false,
      popularity: 0.001,
      gender: 0,
      known_for_department: "Directing",
      profile_path: null,
      known_for: [
        {
          backdrop_path: null,
          id: 733619,
          title: "I Stand At The Doorway",
          original_title: "I Stand At The Doorway",
          overview:
            "Seven girls at an isolated cabin...A killer on the loose...You've heard this story many times before...But what happens after the blood stops spilling?",
          poster_path: null,
          media_type: "movie",
          adult: false,
          original_language: "en",
          genre_ids: [],
          popularity: 0.001,
          release_date: "",
          video: false,
          vote_average: 0,
          vote_count: 0,
        },
      ],
    },
    {
      id: 2993060,
      name: "Squidink",
      original_name: "Squidink",
      media_type: "person",
      adult: false,
      popularity: 0.001,
      gender: 0,
      known_for_department: "Writing",
      profile_path: null,
      known_for: [
        {
          backdrop_path: "/xgQZhEZRlh7ora1sLN24qDNZCqS.jpg",
          id: 801178,
          title: "The Girl with the Blurred Face",
          original_title: "The Girl with the Blurred Face",
          overview:
            "Javier spends most of his time roaming the world on Google Earth. He begins to question his sanity when the same woman keeps appearing in different parts of the world.",
          poster_path: "/fmkh0DN0ERIJp3rg6FOkD5uV6XU.jpg",
          media_type: "movie",
          adult: false,
          original_language: "en",
          genre_ids: [27],
          popularity: 0.029,
          release_date: "2021-09-09",
          video: false,
          vote_average: 0,
          vote_count: 0,
        },
      ],
    },
    {
      id: 4852632,
      name: "Squidscripter",
      original_name: "Squidscripter",
      media_type: "person",
      adult: false,
      popularity: 0.001,
      gender: 0,
      known_for_department: "Acting",
      profile_path: null,
      known_for: [
        {
          backdrop_path: null,
          id: 1322112,
          title: "Lego Among Us",
          original_title: "Lego Among Us",
          overview:
            "An impostor has been detected among a group of astronauts who need to complete their tasks before it's too late!",
          poster_path: "/a0QUax4EEWyhHftZ6xb7HgvEvaL.jpg",
          media_type: "movie",
          adult: false,
          original_language: "en",
          genre_ids: [],
          popularity: 0.014,
          release_date: "2020-10-31",
          video: false,
          vote_average: 0,
          vote_count: 0,
        },
      ],
    },
    {
      id: 4945946,
      name: "Flying Squid",
      original_name: "Flying Squid",
      media_type: "person",
      adult: false,
      popularity: 0.001,
      gender: 0,
      known_for_department: "Sound",
      profile_path: null,
      known_for: [
        {
          backdrop_path: null,
          id: 1094442,
          title: "Jethro's Mirage",
          original_title: "Jethro's Mirage",
          overview:
            "A trio of friends go to Ancient Bethlehem to learn about quicksand. Created for the Bentlcord Experimental Animation Festival.",
          poster_path: "/p9sPNlFzPMGNnfjZAs1vpsIsHSS.jpg",
          media_type: "movie",
          adult: false,
          original_language: "en",
          genre_ids: [16, 12],
          popularity: 0.001,
          release_date: "2022-07-30",
          video: false,
          vote_average: 0,
          vote_count: 0,
        },
      ],
    },
    {
      backdrop_path: null,
      id: 598739,
      title: "Squid",
      original_title: "Кальмар",
      overview:
        "The 30-year-old single Polina always puts first the interests of other people: relatives, acquaintances and her beloved Mitya, who has been married in serious and for a long time. She does not notice that they all manipulate her, solving only their problems. When Polina is attacked and her own life is in danger, she understands that she is no longer a victim and must fight for herself not only in the attack, but also in her everyday life.",
      poster_path: "/yFANim0gZyHLxg8oSKaZWnkh0lr.jpg",
      media_type: "movie",
      adult: false,
      original_language: "ru",
      genre_ids: [18],
      popularity: 0.596,
      release_date: "2019-06-11",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      backdrop_path: "/vdUv6onEaBJ0HsJx3TyFZfzmwxr.jpg",
      id: 1248905,
      title: "Splatoon - Squid Sisters Concert at Japan Expo 2016",
      original_title: "「シオカライブ」フランス公演 in JapanExpo2016",
      overview:
        "The Squid Sisters performed at Japan Expo in Paris on Friday. Check out the show!",
      poster_path: "/i03GlUgXRmtU7gRGp2jfOX2EVh6.jpg",
      media_type: "movie",
      adult: false,
      original_language: "ja",
      genre_ids: [10402, 16],
      popularity: 2.306,
      release_date: "2016-07-12",
      video: false,
      vote_average: 10,
      vote_count: 1,
    },
    {
      backdrop_path: null,
      id: 369452,
      title: "Squid Festival",
      original_title: "納涼アニメ 電球烏賊祭",
      overview:
        "Death is the gateway to birth. The deceased crosses the line to join the kingdom of the dead. He sees there the dance of the sperm and the egg. He is drawn towards the sky. This is the path to the afterlife.",
      poster_path: "/twvFyU9Agi4FeSqNYZK6cIFDcpc.jpg",
      media_type: "movie",
      adult: false,
      original_language: "ja",
      genre_ids: [16],
      popularity: 0.001,
      release_date: "1993-11-20",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
  ],
  total_pages: 3,
  total_results: 58,
};
