const trendingMovies = {
  page: 1,
  results: [
    {
      backdrop_path: "/uKb22E0nlzr914bA9KyA5CVCOlV.jpg",
      id: 402431,
      title: "Wicked",
      original_title: "Wicked",
      overview:
        "In the land of Oz, ostracized and misunderstood green-skinned Elphaba is forced to share a room with the popular aristocrat Glinda at Shiz University, and the two's unlikely friendship is tested as they begin to fulfill their respective destinies as Glinda the Good and the Wicked Witch of the West.",
      poster_path: "/xDGbZ0JJ3mYaGKy4Nzd9Kph6M9L.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [18, 10749, 14],
      popularity: 2260.092,
      release_date: "2024-11-20",
      video: false,
      vote_average: 7.3,
      vote_count: 1147,
    },
    {
      backdrop_path: "/dMloNvayweggmvv0UD0iOJIkkbH.jpg",
      id: 1261501,
      title: "Ad Vitam",
      original_title: "Ad Vitam",
      overview:
        "After escaping an attempted murder, Franck Lazarev must find his wife Léo, who has been kidnapped by a mysterious group of armed men. He is caught up by his past as a former member of the French Elite Intervention Squad and pulled into a state affair far beyond his control.",
      poster_path: "/dOpSxmD3FWfl6SK8SLXw9uwcO05.jpg",
      media_type: "movie",
      adult: false,
      original_language: "fr",
      genre_ids: [53, 18, 80, 28],
      popularity: 41.198,
      release_date: "2025-01-10",
      video: false,
      vote_average: 5.6,
      vote_count: 8,
    },
    {
      backdrop_path: "/b3mdmjYTEL70j7nuXATUAD9qgu4.jpg",
      id: 823219,
      title: "Flow",
      original_title: "Straume",
      overview:
        "A solitary cat, displaced by a great flood, finds refuge on a boat with various species and must navigate the challenges of adapting to a transformed world together.",
      poster_path: "/imKSymKBK7o73sajciEmndJoVkR.jpg",
      media_type: "movie",
      adult: false,
      original_language: "lv",
      genre_ids: [16, 14, 12],
      popularity: 1520.499,
      release_date: "2024-01-30",
      video: false,
      vote_average: 8.4,
      vote_count: 635,
    },
    {
      backdrop_path: "/ic82PQy0hixc6wA5vOaK80lUCDw.jpg",
      id: 1255788,
      title: "The Gardener",
      original_title: "Le Jardinier",
      overview:
        "Every year the Prime Minister has a list of all kinds of troublemakers eliminated in the name of the famous Reason of State. Serge Shuster, Special Adviser to the President of the Republic, finds himself on this list, better known as the Matignon List.  Condemned to certain death and at the heart of an implacable plot and a state secret that also put his family in danger, Serge, his wife and children have only one hope left - their gardener, Léo, who hates it when « slugs » invade his garden... Especially those that want to kill innocent families.",
      poster_path: "/zvLQXaiHn5g376AuHe8hd0u8tN2.jpg",
      media_type: "movie",
      adult: false,
      original_language: "fr",
      genre_ids: [28, 35],
      popularity: 31.797,
      release_date: "2025-01-10",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      backdrop_path: "/uWOJbarUXfVf6B4o0368dh138eR.jpg",
      id: 426063,
      title: "Nosferatu",
      original_title: "Nosferatu",
      overview:
        "A gothic tale of obsession between a haunted young woman and the terrifying vampire infatuated with her, causing untold horror in its wake.",
      poster_path: "/5qGIxdEO841C0tdY8vOdLoRVrr0.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [18, 14, 27],
      popularity: 923.788,
      release_date: "2024-12-25",
      video: false,
      vote_average: 6.9,
      vote_count: 748,
    },
    {
      backdrop_path: "/jgySLjw9ZDKbnGf0VlhlHT7iHSi.jpg",
      id: 936245,
      title: "Hidden Face",
      original_title: "히든페이스",
      overview:
        "Su-yeon, a cellist in an orchestra led by her fiancé and conductor Sung-jin, disappears one day, leaving behind only a video recording. Sung-jin is devastated over the loss of Su-yeon, but feels a strong attraction to Mi-ju, a cellist who fills in for his fiancée. Then one rainy night, Sung-jin and Mi-ju get swept away by their mutual desires for each other and commit an unforgivable act at Su-yeon’s house. Meanwhile, Su-yeon, who is thought to have gone missing, remains trapped in a secret room inside her house, and watches the naked truth unravel before her.",
      poster_path: "/kjLbzQVkQovLpUt4rXiFY2Lv4qM.jpg",
      media_type: "movie",
      adult: false,
      original_language: "ko",
      genre_ids: [9648, 53],
      popularity: 278.989,
      release_date: "2024-11-20",
      video: false,
      vote_average: 3.2,
      vote_count: 11,
    },
    {
      backdrop_path: "/zOpe0eHsq0A2NvNyBbtT6sj53qV.jpg",
      id: 939243,
      title: "Sonic the Hedgehog 3",
      original_title: "Sonic the Hedgehog 3",
      overview:
        "Sonic, Knuckles, and Tails reunite against a powerful new adversary, Shadow, a mysterious villain with powers unlike anything they have faced before. With their abilities outmatched in every way, Team Sonic must seek out an unlikely alliance in hopes of stopping Shadow and protecting the planet.",
      poster_path: "/d8Ryb8AunYAuycVKDp5HpdWPKgC.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 878, 35, 10751],
      popularity: 4115.631,
      release_date: "2024-12-19",
      video: false,
      vote_average: 7.58,
      vote_count: 440,
    },
    {
      backdrop_path: "/vZG7PrX9HmdgL5qfZRjhJsFYEIA.jpg",
      id: 912649,
      title: "Venom: The Last Dance",
      original_title: "Venom: The Last Dance",
      overview:
        "Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision that will bring the curtains down on Venom and Eddie's last dance.",
      poster_path: "/aosm8NMQ3UyoBVpSxyimorCQykC.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 878, 12],
      popularity: 2911.214,
      release_date: "2024-10-22",
      video: false,
      vote_average: 6.801,
      vote_count: 2261,
    },
    {
      backdrop_path: "/7h6TqPB3ESmjuVbxCxAeB1c9OB1.jpg",
      id: 933260,
      title: "The Substance",
      original_title: "The Substance",
      overview:
        "A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself.",
      poster_path: "/lqoMzCcZYEFK729d6qzt349fB4o.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [27, 878],
      popularity: 890.175,
      release_date: "2024-09-07",
      video: false,
      vote_average: 7.138,
      vote_count: 3128,
    },
    {
      backdrop_path: "/ie8OSgIHEl6yQiGJ90dsyBWOpQA.jpg",
      id: 839033,
      title: "The Lord of the Rings: The War of the Rohirrim",
      original_title: "The Lord of the Rings: The War of the Rohirrim",
      overview:
        "A sudden attack by Wulf, a clever and traitorous lord of Rohan seeking vengeance for the death of his father, forces Helm Hammerhand, the King of Rohan, and his people to make a daring last stand in the ancient stronghold of the Hornburg.",
      poster_path: "/cXzCOx1hUuU9CfmiEv6rXjb6EqU.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [16, 14, 28, 12],
      popularity: 1984.581,
      release_date: "2024-12-05",
      video: false,
      vote_average: 6.5,
      vote_count: 276,
    },
    {
      backdrop_path: "/euYIwmwkmz95mnXvufEmbL6ovhZ.jpg",
      id: 558449,
      title: "Gladiator II",
      original_title: "Gladiator II",
      overview:
        "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
      poster_path: "/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 12, 18],
      popularity: 3555.894,
      release_date: "2024-11-05",
      video: false,
      vote_average: 6.77,
      vote_count: 2193,
    },
    {
      backdrop_path: "/hctfNoMpQGfn3VXdBYb9p0P5bT5.jpg",
      id: 1097549,
      title: "Babygirl",
      original_title: "Babygirl",
      overview:
        "A high-powered CEO puts her career and family on the line when she begins a torrid affair with her much younger intern.",
      poster_path: "/A8HbTd0FemZyFCh5qvJFpHGiwF8.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [18],
      popularity: 288.367,
      release_date: "2024-12-25",
      video: false,
      vote_average: 5.6,
      vote_count: 45,
    },
    {
      backdrop_path: "/oHPoF0Gzu8xwK4CtdXDaWdcuZxZ.jpg",
      id: 762509,
      title: "Mufasa: The Lion King",
      original_title: "Mufasa: The Lion King",
      overview:
        "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
      poster_path: "/iBqXjFkAozQ1z2sfAiWwBimbiJX.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [12, 10751, 16],
      popularity: 2684.622,
      release_date: "2024-12-18",
      video: false,
      vote_average: 7.4,
      vote_count: 551,
    },
    {
      backdrop_path: "/nGC3ZkXEcjGbqAAonS1xn6gaNpb.jpg",
      id: 1013850,
      title: "A Real Pain",
      original_title: "A Real Pain",
      overview:
        "Mismatched cousins David and Benji reunite for a tour through Poland to honor their beloved grandmother. The adventure takes a turn when the pair's old tensions resurface against the backdrop of their family history.",
      poster_path: "/67xRIXm5TxXRT4nV2V4AEJ9yq2d.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [35, 18],
      popularity: 552.942,
      release_date: "2024-11-01",
      video: false,
      vote_average: 6.7,
      vote_count: 143,
    },
    {
      backdrop_path: "/8DwV1DCZtqJNkEsRWE1d0ZmI2Is.jpg",
      id: 929204,
      title: "Wallace & Gromit: Vengeance Most Fowl",
      original_title: "Wallace & Gromit: Vengeance Most Fowl",
      overview:
        "Gromit’s concern that Wallace is becoming too dependent on his inventions proves justified, when Wallace invents a “smart” gnome that seems to develop a mind of its own. When it emerges that a vengeful figure from the past might be masterminding things, it falls to Gromit to battle sinister forces and save his master… or Wallace may never be able to invent again!",
      poster_path: "/6BxK38ehxuX2dJmZIMpJcVNbYks.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [16, 35, 10751, 12],
      popularity: 720.905,
      release_date: "2024-12-18",
      video: false,
      vote_average: 7.815,
      vote_count: 203,
    },
    {
      backdrop_path: "/1pmXyN3sKeYoUhu5VBZiDU4BX21.jpg",
      id: 1184918,
      title: "The Wild Robot",
      original_title: "The Wild Robot",
      overview:
        "After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island. To survive the harsh environment, Roz bonds with the island's animals and cares for an orphaned baby goose.",
      poster_path: "/9w0Vh9eizfBXrcomiaFWTIPdboo.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [16, 28, 878, 10751],
      popularity: 718.614,
      release_date: "2024-09-12",
      video: false,
      vote_average: 8.373,
      vote_count: 3878,
    },
    {
      backdrop_path: "/4cp40IyTpFfsT2IKpl0YlUkMBIR.jpg",
      id: 1064213,
      title: "Anora",
      original_title: "Anora",
      overview:
        "A young sex worker from Brooklyn gets her chance at a Cinderella story when she meets and impulsively marries the son of an oligarch. Once the news reaches Russia, her fairytale is threatened as his parents set out to get the marriage annulled.",
      poster_path: "/7MrgIUeq0DD2iF7GR6wqJfYZNeC.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [10749, 35, 18],
      popularity: 409.659,
      release_date: "2024-10-14",
      video: false,
      vote_average: 6.9,
      vote_count: 679,
    },
    {
      backdrop_path: "/9REO1DLpmwhrBJY3mYW5eVxkXFM.jpg",
      id: 157336,
      title: "Interstellar",
      original_title: "Interstellar",
      overview:
        "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
      poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [12, 18, 878],
      popularity: 388.942,
      release_date: "2014-11-05",
      video: false,
      vote_average: 8.4,
      vote_count: 36051,
    },
    {
      backdrop_path: "/tElnmtQ6yz1PjN1kePNl8yMSb59.jpg",
      id: 1241982,
      title: "Moana 2",
      original_title: "Moana 2",
      overview:
        "After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she's ever faced.",
      poster_path: "/m0SbwFNCa9epW1X60deLqTHiP7x.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [16, 12, 10751, 35],
      popularity: 2127.698,
      release_date: "2024-11-21",
      video: false,
      vote_average: 7.01,
      vote_count: 802,
    },
    {
      backdrop_path: "/66nlC5LDZmDUWONGkUZT2BrOszG.jpg",
      id: 974576,
      title: "Conclave",
      original_title: "Conclave",
      overview:
        "After the unexpected death of the Pope, Cardinal Lawrence is tasked with managing the covert and ancient ritual of electing a new one. Sequestered in the Vatican with the Catholic Church’s most powerful leaders until the process is complete, Lawrence finds himself at the center of a conspiracy that could lead to its downfall.",
      poster_path: "/m5x8D0bZ3eKqIVWZ5y7TnZ2oTVg.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [18],
      popularity: 234.58,
      release_date: "2024-10-25",
      video: false,
      vote_average: 7.1,
      vote_count: 758,
    },
  ],
  total_pages: 500,
  total_results: 10000,
};
