const trendingSeries = {
  page: 1,
  results: [
    {
      backdrop_path: "/1FxG2lmDYsCM1svJf7H79HNNwu2.jpg",
      id: 215866,
      name: "American Primeval",
      original_name: "American Primeval",
      overview:
        "A mother and son fleeing from their past form a found family while confronting a harsh landscape of freedom and cruelty in the American West.",
      poster_path: "/ff0s9OHGNSZL6cVteIb7LNvTnJD.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [37, 18, 10759],
      popularity: 130.698,
      first_air_date: "2025-01-09",
      vote_average: 7.1,
      vote_count: 24,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/sMhDkrG904UcMJyrUtTuJVlsBJq.jpg",
      id: 236429,
      name: "On Call",
      original_name: "On Call",
      overview:
        "Traci Harmon, a veteran female training officer, and her rookie male ride-along, Alex Diaz, navigate the loss of a fellow officer and politics of modern day policing  — in the department and on the streets of Long Beach.",
      poster_path: "/3MvgPuQfBrJ54lGqTZ6dwhG61rC.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [80, 18, 10759],
      popularity: 94.493,
      first_air_date: "2025-01-09",
      vote_average: 7.9,
      vote_count: 17,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/ukAmSyNdtWduHZfm27R2EOsguKt.jpg",
      id: 93405,
      name: "Squid Game",
      original_name: "오징어 게임",
      overview:
        "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits — with deadly high stakes.",
      poster_path: "/1QdXdRYfktUSONkl1oD5gc6Be0s.jpg",
      media_type: "tv",
      adult: false,
      original_language: "ko",
      genre_ids: [10759, 9648, 18],
      popularity: 8435.793,
      first_air_date: "2021-09-17",
      vote_average: 7.8,
      vote_count: 14834,
      origin_country: ["KR"],
    },
    {
      backdrop_path: "/25yx86n5RrmcmgxFPWWHFcMnMnd.jpg",
      id: 157004,
      name: "Goosebumps",
      original_name: "Goosebumps",
      overview:
        "A group of five high schoolers embark on a shadowy and twisted journey to investigate the tragic passing three decades earlier of a teen named Harold Biddle – while also unearthing dark secrets from their parents' past.",
      poster_path: "/aIR1prPYBi8dBbJc5IKEK88uVOE.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [10759, 10765, 35],
      popularity: 134.526,
      first_air_date: "2023-10-13",
      vote_average: 7.2,
      vote_count: 153,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/lN13BPAEnc5iXmoxxBQHOZ1ScfZ.jpg",
      id: 86031,
      name: "Dr. STONE",
      original_name: "Dr.STONE",
      overview:
        "One fateful day, all of humanity was petrified by a blinding flash of light. After several millennia, high schooler Taiju awakens and finds himself lost in a world of statues. However, he's not alone! His science-loving friend Senku's been up and running for a few months and he's got a grand plan in mind, to kickstart civilization with the power of science!",
      poster_path: "/xbZQ3fDl0y5mt0ARwfeyrgQ4JTw.jpg",
      media_type: "tv",
      adult: false,
      original_language: "ja",
      genre_ids: [10759, 16, 35, 10765],
      popularity: 54.769,
      first_air_date: "2019-07-05",
      vote_average: 8.5,
      vote_count: 1452,
      origin_country: ["JP"],
    },
    {
      backdrop_path: "/z3BkMbCy5ajZPMyKEUwsPHuz2cV.jpg",
      id: 250307,
      name: "The Pitt",
      original_name: "The Pitt",
      overview:
        "The staff of Pittsburgh's Trauma Medical Center work around the clock to save lives in an overcrowded and underfunded emergency department.",
      poster_path: "/6fMGktEDXMZZPACJ5cWkVQ6TSte.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [18],
      popularity: 74.105,
      first_air_date: "2025-01-09",
      vote_average: 7.8,
      vote_count: 6,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/n5FPNMJ0eRoiQrKGfUQQRAZeaxg.jpg",
      id: 125988,
      name: "Silo",
      original_name: "Silo",
      overview:
        "In a ruined and toxic future, thousands live in a giant silo deep underground. After its sheriff breaks a cardinal rule and residents die mysteriously, engineer Juliette starts to uncover shocking secrets and the truth about the silo.",
      poster_path: "/tlliQuCupf8fpTH7RAor3aKMGy.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [10765, 18],
      popularity: 1015.695,
      first_air_date: "2023-05-04",
      vote_average: 8.166,
      vote_count: 1233,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/y8T8BhptuHFPR0hCGcUSMyUfUfm.jpg",
      id: 219543,
      name: "Creature Commandos",
      original_name: "Creature Commandos",
      overview:
        "Follow the exploits of the Creature Commandos, a secret team of incarcerated monsters recruited for missions deemed too dangerous for humans. When all else fails... they're your last, worst option.",
      poster_path: "/bB3G6Ug1jfsOUptb0RJsqrgMVta.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [16, 10765, 10759],
      popularity: 527.08,
      first_air_date: "2024-12-05",
      vote_average: 8.207,
      vote_count: 94,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/sbBiDH41uDR2PlRtdCYT5c3inyp.jpg",
      id: 277805,
      name: "Subteran",
      original_name: "Subteran",
      overview:
        "A young mother's life is upended when she finds herself hiding behind a secret identity to escape the Bucharest gang responsible for her fiancé's death.",
      poster_path: "/zLpmZeJNST8bbiHzFwOY1wcJA4u.jpg",
      media_type: "tv",
      adult: false,
      original_language: "ro",
      genre_ids: [80, 18],
      popularity: 72.867,
      first_air_date: "2025-01-08",
      vote_average: 8.3,
      vote_count: 6,
      origin_country: ["RO"],
    },
    {
      backdrop_path: "/hOrMnYizPOfh9w2SMYoeezCCFSV.jpg",
      id: 230127,
      name: "Hound's Hill",
      original_name: "Wzgórze psów",
      overview:
        "A successful and renowned novelist — haunted by trauma and a mysterious blackmailer — returns to his hometown to reckon with his unresolved past.",
      poster_path: "/gLLVz7NFxUERSIVvn6Pap9ZMc5w.jpg",
      media_type: "tv",
      adult: false,
      original_language: "pl",
      genre_ids: [9648, 80, 18],
      popularity: 91.23,
      first_air_date: "2025-01-08",
      vote_average: 8.7,
      vote_count: 6,
      origin_country: ["PL"],
    },
    {
      backdrop_path: "/odVlTMqPPiMksmxpN9cCbPCjUPP.jpg",
      id: 127532,
      name: "Solo Leveling",
      original_name: "俺だけレベルアップな件",
      overview:
        "They say whatever doesn’t kill you makes you stronger, but that’s not the case for the world’s weakest hunter Sung Jinwoo. After being brutally slaughtered by monsters in a high-ranking dungeon, Jinwoo came back with the System, a program only he could see, that’s leveling him up in every way. Now, he’s inspired to discover the secrets behind his powers and the dungeon that spawned them.",
      poster_path: "/geCRueV3ElhRTr0xtJuEWJt6dJ1.jpg",
      media_type: "tv",
      adult: false,
      original_language: "ja",
      genre_ids: [10759, 10765, 16],
      popularity: 833.367,
      first_air_date: "2024-01-07",
      vote_average: 8.506,
      vote_count: 582,
      origin_country: ["JP"],
    },
    {
      backdrop_path: "/lJuQBW4w1x6NgD514xDPqZ2Lbpz.jpg",
      id: 220542,
      name: "The Apothecary Diaries",
      original_name: "薬屋のひとりごと",
      overview:
        "Maomao lived a peaceful life with her apothecary father. Until one day, she's sold as a lowly servant to the emperor's palace. But she wasn't meant for a compliant life among royalty. So when imperial heirs fall ill, she decides to step in and find a cure! This catches the eye of Jinshi, a handsome palace official who promotes her. Now, she's making a name for herself solving medical mysteries!",
      poster_path: "/e3ojpANrFnmJCyeBNTinYwyBCIN.jpg",
      media_type: "tv",
      adult: false,
      original_language: "ja",
      genre_ids: [16, 18, 9648],
      popularity: 249.192,
      first_air_date: "2023-10-22",
      vote_average: 8.814,
      vote_count: 212,
      origin_country: ["JP"],
    },
    {
      backdrop_path: "/801476SmpE20vPI5sz9H5vgBYBq.jpg",
      id: 239137,
      name: "Asura",
      original_name: "阿修羅のごとく",
      overview:
        "In 1979 Tokyo, four distinct sisters uncover their aging father's affair, causing their happy facades and bottled-up emotions to slowly unravel.",
      poster_path: "/6d4IrjS3t3O7dFynAmrLKXrSNwe.jpg",
      media_type: "tv",
      adult: false,
      original_language: "ja",
      genre_ids: [18],
      popularity: 65.757,
      first_air_date: "2025-01-09",
      vote_average: 6,
      vote_count: 1,
      origin_country: ["JP"],
    },
    {
      backdrop_path: "/aTk5XhDb4vdqVXBiatmpbdDJIVK.jpg",
      id: 270474,
      name: 'Even Given the Worthless "Appraiser" Class, I\'m Actually the Strongest',
      original_name:
        "不遇職【鑑定士】が実は最強だった～奈落で鍛えた最強の【神眼】で無双する～",
      overview:
        "In a world where heroes are born, not made, Ein’s god-given gift is the weakest: the power to appraise things. Treated cruelly by his peers, Ein spends his days in self-abasement—until he meets Yuri, the spirit of the World Tree. Yuri and her protector, Ursula, bless Ein with the Spirit Eye, unlocking new strength. As his abilities grow, Ein embarks on a journey to uncover his true purpose.",
      poster_path: "/lUAGrruGGj2PB6CYkw6tGLQD41G.jpg",
      media_type: "tv",
      adult: false,
      original_language: "ja",
      genre_ids: [10759, 16, 10765, 18],
      popularity: 84.662,
      first_air_date: "2025-01-09",
      vote_average: 8,
      vote_count: 1,
      origin_country: ["JP"],
    },
    {
      backdrop_path: "/6E0hbesJfpekAqL2AeHYukkHcbD.jpg",
      id: 202879,
      name: "Star Wars: Skeleton Crew",
      original_name: "Star Wars: Skeleton Crew",
      overview:
        "Four ordinary kids search for their home planet after getting lost in the Star Wars galaxy.",
      poster_path: "/srQbJhLRKoAwRrNN5ga7webPHbC.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [10759, 10765],
      popularity: 639.251,
      first_air_date: "2024-12-02",
      vote_average: 7.301,
      vote_count: 136,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/7e7GKWe49a8g96KP037PcrGtG6I.jpg",
      id: 227371,
      name: "Fake Profile",
      original_name: "Perfil falso",
      overview:
        "Camila meets her Prince Charming through a dating app. After an idyllic romance, she plans to surprise him — only to end up trapped in a false paradise.",
      poster_path: "/3KyyfuG5VxUmpJFnw0pa1SkTsuL.jpg",
      media_type: "tv",
      adult: false,
      original_language: "es",
      genre_ids: [18],
      popularity: 382.924,
      first_air_date: "2023-05-31",
      vote_average: 7.5,
      vote_count: 138,
      origin_country: ["CO"],
    },
    {
      backdrop_path: "/5JbWk5f3zSbwkQjbCazWi1adDMl.jpg",
      id: 233912,
      name: "Guardians of the Dafeng",
      original_name: "大奉打更人",
      overview:
        "Xu Qi’an, a recent police academy graduate, awakens in a strange world filled with Confucians, Taoists, Buddhists, demons, and warlocks. Facing imminent exile to a remote frontier town, he seizes the chance to change his fate by joining a powerful organization of guardians.",
      poster_path: "/zhIvZOCzwjJdn1Xu2KWikC7Luiq.jpg",
      media_type: "tv",
      adult: false,
      original_language: "zh",
      genre_ids: [18, 10759, 35],
      popularity: 2384.688,
      first_air_date: "2024-12-28",
      vote_average: 7,
      vote_count: 7,
      origin_country: ["CN"],
    },
    {
      backdrop_path: "/hGrWgrPb80Mbbx3hFqsf0welxLu.jpg",
      id: 258680,
      name: "Anyway, I'm Falling in Love with You.",
      original_name: "どうせ、恋してしまうんだ。",
      overview:
        "It’s the year 2020, and Mizuho is having the worst 17th birthday ever. Her parents forgot it’s her birthday, she still can’t seem to get close to the senior she likes, and all her school trips and tournaments are canceled thanks to a new disease going around. She’s convinced she’ll never have the kind of youth she’s always dreamt of…until her childhood friend, Kizuki, suddenly asks her out.",
      poster_path: "/1l2M78uA4oCqJImxnvrsSyjXzF6.jpg",
      media_type: "tv",
      adult: false,
      original_language: "ja",
      genre_ids: [16, 18],
      popularity: 41.451,
      first_air_date: "2025-01-10",
      vote_average: 0,
      vote_count: 0,
      origin_country: ["JP"],
    },
    {
      backdrop_path: "/2Fi1IRNripElbkCFKsx6AlHh5JL.jpg",
      id: 258912,
      name: "Magic Maker: How to Make Magic in Another World",
      original_name: "マジック・メイカー ～異世界魔法の作り方～",
      overview:
        "On the night of his 30th birthday, one man’s dreams of wielding magic come true after he unexpectedly passes away. He wakes as Sion, a young child in another world. He and his elder sister, Marie, are the children of a lower-class noble family who govern their region. After receiving conflicting messages from their father, Sion and Marie set out on an adventure to uncover the magic.",
      poster_path: "/wKe1FmUAcSukpfEn5s6747pBwLD.jpg",
      media_type: "tv",
      adult: false,
      original_language: "ja",
      genre_ids: [16, 10765, 10759, 35],
      popularity: 75.646,
      first_air_date: "2025-01-09",
      vote_average: 10,
      vote_count: 1,
      origin_country: ["JP"],
    },
    {
      backdrop_path: "/2QDzGUUuGMyvdLBIcgx923mqRrf.jpg",
      id: 279283,
      name: "The Breakthrough",
      original_name: "Genombrottet",
      overview:
        "When a shocking double homicide goes unsolved for 16 years, a detective teams up with a genealogist to catch the killer before it becomes a cold case.",
      poster_path: "/5gYhNl5XAPOw36qjxg3mOXxeKoq.jpg",
      media_type: "tv",
      adult: false,
      original_language: "sv",
      genre_ids: [18, 80],
      popularity: 142.265,
      first_air_date: "2025-01-07",
      vote_average: 7.1,
      vote_count: 20,
      origin_country: ["SE"],
    },
  ],
  total_pages: 500,
  total_results: 10000,
};
