const trendingAll = {
  page: 1,
  results: [
    {
      backdrop_path: "/1FxG2lmDYsCM1svJf7H79HNNwu2.jpg",
      id: 215866,
      name: "American Primeval",
      original_name: "American Primeval",
      overview:
        "A mother and son fleeing from their past form a found family while confronting a harsh landscape of freedom and cruelty in the American West.",
      poster_path: "/ff0s9OHGNSZL6cVteIb7LNvTnJD.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [37, 18, 10759],
      popularity: 130.698,
      first_air_date: "2025-01-09",
      vote_average: 7.1,
      vote_count: 24,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/sMhDkrG904UcMJyrUtTuJVlsBJq.jpg",
      id: 236429,
      name: "On Call",
      original_name: "On Call",
      overview:
        "Traci Harmon, a veteran female training officer, and her rookie male ride-along, Alex Diaz, navigate the loss of a fellow officer and politics of modern day policing  — in the department and on the streets of Long Beach.",
      poster_path: "/3MvgPuQfBrJ54lGqTZ6dwhG61rC.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [80, 18, 10759],
      popularity: 94.493,
      first_air_date: "2025-01-09",
      vote_average: 7.9,
      vote_count: 17,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/uKb22E0nlzr914bA9KyA5CVCOlV.jpg",
      id: 402431,
      title: "Wicked",
      original_title: "Wicked",
      overview:
        "In the land of Oz, ostracized and misunderstood green-skinned Elphaba is forced to share a room with the popular aristocrat Glinda at Shiz University, and the two's unlikely friendship is tested as they begin to fulfill their respective destinies as Glinda the Good and the Wicked Witch of the West.",
      poster_path: "/xDGbZ0JJ3mYaGKy4Nzd9Kph6M9L.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [18, 10749, 14],
      popularity: 2260.092,
      release_date: "2024-11-20",
      video: false,
      vote_average: 7.3,
      vote_count: 1147,
    },
    {
      backdrop_path: "/ukAmSyNdtWduHZfm27R2EOsguKt.jpg",
      id: 93405,
      name: "Squid Game",
      original_name: "오징어 게임",
      overview:
        "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits — with deadly high stakes.",
      poster_path: "/1QdXdRYfktUSONkl1oD5gc6Be0s.jpg",
      media_type: "tv",
      adult: false,
      original_language: "ko",
      genre_ids: [10759, 9648, 18],
      popularity: 8435.793,
      first_air_date: "2021-09-17",
      vote_average: 7.8,
      vote_count: 14834,
      origin_country: ["KR"],
    },
    {
      backdrop_path: "/25yx86n5RrmcmgxFPWWHFcMnMnd.jpg",
      id: 157004,
      name: "Goosebumps",
      original_name: "Goosebumps",
      overview:
        "A group of five high schoolers embark on a shadowy and twisted journey to investigate the tragic passing three decades earlier of a teen named Harold Biddle – while also unearthing dark secrets from their parents' past.",
      poster_path: "/aIR1prPYBi8dBbJc5IKEK88uVOE.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [10759, 10765, 35],
      popularity: 134.526,
      first_air_date: "2023-10-13",
      vote_average: 7.2,
      vote_count: 153,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/dMloNvayweggmvv0UD0iOJIkkbH.jpg",
      id: 1261501,
      title: "Ad Vitam",
      original_title: "Ad Vitam",
      overview:
        "After escaping an attempted murder, Franck Lazarev must find his wife Léo, who has been kidnapped by a mysterious group of armed men. He is caught up by his past as a former member of the French Elite Intervention Squad and pulled into a state affair far beyond his control.",
      poster_path: "/dOpSxmD3FWfl6SK8SLXw9uwcO05.jpg",
      media_type: "movie",
      adult: false,
      original_language: "fr",
      genre_ids: [53, 18, 80, 28],
      popularity: 41.198,
      release_date: "2025-01-10",
      video: false,
      vote_average: 5.6,
      vote_count: 8,
    },
    {
      backdrop_path: "/b3mdmjYTEL70j7nuXATUAD9qgu4.jpg",
      id: 823219,
      title: "Flow",
      original_title: "Straume",
      overview:
        "A solitary cat, displaced by a great flood, finds refuge on a boat with various species and must navigate the challenges of adapting to a transformed world together.",
      poster_path: "/imKSymKBK7o73sajciEmndJoVkR.jpg",
      media_type: "movie",
      adult: false,
      original_language: "lv",
      genre_ids: [16, 14, 12],
      popularity: 1520.499,
      release_date: "2024-01-30",
      video: false,
      vote_average: 8.4,
      vote_count: 635,
    },
    {
      backdrop_path: "/lN13BPAEnc5iXmoxxBQHOZ1ScfZ.jpg",
      id: 86031,
      name: "Dr. STONE",
      original_name: "Dr.STONE",
      overview:
        "One fateful day, all of humanity was petrified by a blinding flash of light. After several millennia, high schooler Taiju awakens and finds himself lost in a world of statues. However, he's not alone! His science-loving friend Senku's been up and running for a few months and he's got a grand plan in mind, to kickstart civilization with the power of science!",
      poster_path: "/xbZQ3fDl0y5mt0ARwfeyrgQ4JTw.jpg",
      media_type: "tv",
      adult: false,
      original_language: "ja",
      genre_ids: [10759, 16, 35, 10765],
      popularity: 54.769,
      first_air_date: "2019-07-05",
      vote_average: 8.5,
      vote_count: 1452,
      origin_country: ["JP"],
    },
    {
      backdrop_path: "/n5FPNMJ0eRoiQrKGfUQQRAZeaxg.jpg",
      id: 125988,
      name: "Silo",
      original_name: "Silo",
      overview:
        "In a ruined and toxic future, thousands live in a giant silo deep underground. After its sheriff breaks a cardinal rule and residents die mysteriously, engineer Juliette starts to uncover shocking secrets and the truth about the silo.",
      poster_path: "/tlliQuCupf8fpTH7RAor3aKMGy.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [10765, 18],
      popularity: 1015.695,
      first_air_date: "2023-05-04",
      vote_average: 8.166,
      vote_count: 1233,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/z3BkMbCy5ajZPMyKEUwsPHuz2cV.jpg",
      id: 250307,
      name: "The Pitt",
      original_name: "The Pitt",
      overview:
        "The staff of Pittsburgh's Trauma Medical Center work around the clock to save lives in an overcrowded and underfunded emergency department.",
      poster_path: "/6fMGktEDXMZZPACJ5cWkVQ6TSte.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [18],
      popularity: 74.105,
      first_air_date: "2025-01-09",
      vote_average: 7.8,
      vote_count: 6,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/ic82PQy0hixc6wA5vOaK80lUCDw.jpg",
      id: 1255788,
      title: "The Gardener",
      original_title: "Le Jardinier",
      overview:
        "Every year the Prime Minister has a list of all kinds of troublemakers eliminated in the name of the famous Reason of State. Serge Shuster, Special Adviser to the President of the Republic, finds himself on this list, better known as the Matignon List.  Condemned to certain death and at the heart of an implacable plot and a state secret that also put his family in danger, Serge, his wife and children have only one hope left - their gardener, Léo, who hates it when « slugs » invade his garden... Especially those that want to kill innocent families.",
      poster_path: "/zvLQXaiHn5g376AuHe8hd0u8tN2.jpg",
      media_type: "movie",
      adult: false,
      original_language: "fr",
      genre_ids: [28, 35],
      popularity: 31.797,
      release_date: "2025-01-10",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      backdrop_path: "/uWOJbarUXfVf6B4o0368dh138eR.jpg",
      id: 426063,
      title: "Nosferatu",
      original_title: "Nosferatu",
      overview:
        "A gothic tale of obsession between a haunted young woman and the terrifying vampire infatuated with her, causing untold horror in its wake.",
      poster_path: "/5qGIxdEO841C0tdY8vOdLoRVrr0.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [18, 14, 27],
      popularity: 923.788,
      release_date: "2024-12-25",
      video: false,
      vote_average: 6.9,
      vote_count: 748,
    },
    {
      backdrop_path: "/y8T8BhptuHFPR0hCGcUSMyUfUfm.jpg",
      id: 219543,
      name: "Creature Commandos",
      original_name: "Creature Commandos",
      overview:
        "Follow the exploits of the Creature Commandos, a secret team of incarcerated monsters recruited for missions deemed too dangerous for humans. When all else fails... they're your last, worst option.",
      poster_path: "/bB3G6Ug1jfsOUptb0RJsqrgMVta.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [16, 10765, 10759],
      popularity: 527.08,
      first_air_date: "2024-12-05",
      vote_average: 8.207,
      vote_count: 94,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/sbBiDH41uDR2PlRtdCYT5c3inyp.jpg",
      id: 277805,
      name: "Subteran",
      original_name: "Subteran",
      overview:
        "A young mother's life is upended when she finds herself hiding behind a secret identity to escape the Bucharest gang responsible for her fiancé's death.",
      poster_path: "/zLpmZeJNST8bbiHzFwOY1wcJA4u.jpg",
      media_type: "tv",
      adult: false,
      original_language: "ro",
      genre_ids: [80, 18],
      popularity: 72.867,
      first_air_date: "2025-01-08",
      vote_average: 8.3,
      vote_count: 6,
      origin_country: ["RO"],
    },
    {
      backdrop_path: "/jgySLjw9ZDKbnGf0VlhlHT7iHSi.jpg",
      id: 936245,
      title: "Hidden Face",
      original_title: "히든페이스",
      overview:
        "Su-yeon, a cellist in an orchestra led by her fiancé and conductor Sung-jin, disappears one day, leaving behind only a video recording. Sung-jin is devastated over the loss of Su-yeon, but feels a strong attraction to Mi-ju, a cellist who fills in for his fiancée. Then one rainy night, Sung-jin and Mi-ju get swept away by their mutual desires for each other and commit an unforgivable act at Su-yeon’s house. Meanwhile, Su-yeon, who is thought to have gone missing, remains trapped in a secret room inside her house, and watches the naked truth unravel before her.",
      poster_path: "/kjLbzQVkQovLpUt4rXiFY2Lv4qM.jpg",
      media_type: "movie",
      adult: false,
      original_language: "ko",
      genre_ids: [9648, 53],
      popularity: 278.989,
      release_date: "2024-11-20",
      video: false,
      vote_average: 3.2,
      vote_count: 11,
    },
    {
      backdrop_path: "/vZG7PrX9HmdgL5qfZRjhJsFYEIA.jpg",
      id: 912649,
      title: "Venom: The Last Dance",
      original_title: "Venom: The Last Dance",
      overview:
        "Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision that will bring the curtains down on Venom and Eddie's last dance.",
      poster_path: "/aosm8NMQ3UyoBVpSxyimorCQykC.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 878, 12],
      popularity: 2911.214,
      release_date: "2024-10-22",
      video: false,
      vote_average: 6.801,
      vote_count: 2261,
    },
    {
      backdrop_path: "/zOpe0eHsq0A2NvNyBbtT6sj53qV.jpg",
      id: 939243,
      title: "Sonic the Hedgehog 3",
      original_title: "Sonic the Hedgehog 3",
      overview:
        "Sonic, Knuckles, and Tails reunite against a powerful new adversary, Shadow, a mysterious villain with powers unlike anything they have faced before. With their abilities outmatched in every way, Team Sonic must seek out an unlikely alliance in hopes of stopping Shadow and protecting the planet.",
      poster_path: "/d8Ryb8AunYAuycVKDp5HpdWPKgC.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 878, 35, 10751],
      popularity: 4115.631,
      release_date: "2024-12-19",
      video: false,
      vote_average: 7.6,
      vote_count: 439,
    },
    {
      backdrop_path: "/hOrMnYizPOfh9w2SMYoeezCCFSV.jpg",
      id: 230127,
      name: "Hound's Hill",
      original_name: "Wzgórze psów",
      overview:
        "A successful and renowned novelist — haunted by trauma and a mysterious blackmailer — returns to his hometown to reckon with his unresolved past.",
      poster_path: "/gLLVz7NFxUERSIVvn6Pap9ZMc5w.jpg",
      media_type: "tv",
      adult: false,
      original_language: "pl",
      genre_ids: [9648, 80, 18],
      popularity: 91.23,
      first_air_date: "2025-01-08",
      vote_average: 8.7,
      vote_count: 6,
      origin_country: ["PL"],
    },
    {
      backdrop_path: "/7h6TqPB3ESmjuVbxCxAeB1c9OB1.jpg",
      id: 933260,
      title: "The Substance",
      original_title: "The Substance",
      overview:
        "A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself.",
      poster_path: "/lqoMzCcZYEFK729d6qzt349fB4o.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [27, 878],
      popularity: 890.175,
      release_date: "2024-09-07",
      video: false,
      vote_average: 7.138,
      vote_count: 3128,
    },
    {
      backdrop_path: "/odVlTMqPPiMksmxpN9cCbPCjUPP.jpg",
      id: 127532,
      name: "Solo Leveling",
      original_name: "俺だけレベルアップな件",
      overview:
        "They say whatever doesn’t kill you makes you stronger, but that’s not the case for the world’s weakest hunter Sung Jinwoo. After being brutally slaughtered by monsters in a high-ranking dungeon, Jinwoo came back with the System, a program only he could see, that’s leveling him up in every way. Now, he’s inspired to discover the secrets behind his powers and the dungeon that spawned them.",
      poster_path: "/geCRueV3ElhRTr0xtJuEWJt6dJ1.jpg",
      media_type: "tv",
      adult: false,
      original_language: "ja",
      genre_ids: [10759, 10765, 16],
      popularity: 833.367,
      first_air_date: "2024-01-07",
      vote_average: 8.506,
      vote_count: 582,
      origin_country: ["JP"],
    },
  ],
  total_pages: 500,
  total_results: 10000,
};
